### ISSUE TITLE
覆盖文件后运行TricolourLovestory_chs.exe报错

### ISSUE THREAD

**Issue by Kv-203** [Darel777/Tri_TE#3]
![屏幕截图 2024-05-05 212427](https://github.com/Darel777/Tri_TE/assets/123849846/8abbd6ec-8fe1-4618-81a4-631a6124422b)
![屏幕截图 2024-05-05 212517](https://github.com/Darel777/Tri_TE/assets/123849846/1f2ec1db-2e79-4df1-8fb8-aae80530a35d)

**Comment by Darel777** [comment]
尝试重新解压并覆盖到Tricolour lovestory中试试 可能是解压过程中数据出现了破损

**Comment by Kv-203** [comment]
在贴吧找到了解决方案，应该是原版游戏的问题

win+i打开电脑设置
在设置中找到语言
看到语言右上角有个“管理语言设置”
点进去看到下面“更改系统区域设置”
把里面bata的勾去掉

https://tieba.baidu.com/p/8219024001?share=9105&fr=sharewise&see_lz=0&share_from=post&sfc=copy&client_type=2&client_version=12.59.1.0&st=1714917800&is_video=false&unique=36924637219AC499C61A6AD3B761754D

**Comment by Darel777** [comment]
感谢您的反馈！
